spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true 
  activemq:
    broker-url: tcp://172.17.0.3:61616
    pooled: true
    

camel:
  springboot:
    type-conversion: true
    