server:
  port: 8081

spring:
  activemq:
    packages:
      trust-all: true
    broker-url: tcp://172.17.0.2:61616
    pool:
      enabled: true
      
camel:
  springboot:
    type-conversion: true